### ISSUE TITLE
Build and integrate an invite and recommendation system

### ISSUE THREAD

**Issue by ALuhning** [VitalPointAI/Catalyst#1]
### Situation
DAOs built with Catalyst will only be useful if they are able to attract and integrate members interested in being part of their community or joining their cause.  While that can be done through word of mouth or other methods - the fact that Catalyst requires a NEAR account to interact with any particular DAO is an added cognitive burden and potential blocker for widespread use outside of those familiar to crypto/NEAR. 

### Mission
Make it easy for DAO owners and their members to invite others to join the DAO in order to increase the utility and use of the DAOs/communities created using Catalyst.

#### Intent
In the interest of better onboarding/attracting people to Catalyst DAOs and their communities, we want to provide both DAO creators and existing members of DAOs with the ability to easily invite people to join them.  This invite/recommendation system should completely eliminate any complexity associated with initial creation/using of a NEAR account before proceeding to the membership proposal component of a Catalyst DAO.  It will enable outreach across the major existing communication platforms including web 2.0 social media (Facebook, Instagram, Twitter, etc...), popular chat platforms (Telegram, Signal, What's App, etc...), email, SMS or any other platform where someone may want to attract users from.  Enabling owners and members to easily invite their friends and colleagues should significantly increase the utility of Catalyst DAOs and exponentially start attracting people to the platform.

#### Scheme of Maneuver
Those wishing to accept/tackle the project will:

1. Leave a comment below indicating willingness to take on the project, estimated time to delivery, and suggested payment (in NEAR).
2. Provide the Github repo for the project - will be used to monitor commits/progress.
3. If this is your first time working with Vital Point AI - **Send 10 NEAR to vitalpointai.near as a deposit.**  You will get this back when the project is delivered (or when it's clear you're serious about completing it).  This is necessary to keep development on track.  It creates a little more incentive for people to avoid having people saying they will work on something and then not - effectively taking the opportunity away from someone who is serious.  You will also get it back if you decide at some point to stop working on the project as long as you let me know so the project can be reassigned.

**When Catalyst is operational, these development opportunities will be managed through a DAO.  Watch for it.

#### Main Effort
working modular invite system with exceptional UX

#### End State (Acceptance Criteria)
When complete, this invite system will:
- [ ] seamlessly integrated with Catalyst platform
- [ ] be of modular design - should be able to plug into another application with minor modifications
- [ ] easy to use UI/good UX (React based)
- [ ] allows members/DAO owners to invite/recommend new people join their DAOs
- [ ] onboards potential members that do not have NEAR accounts (creates an account/gets them into the member proposal workflow of a Catalyst DAO)
- [ ] useable to invite/recommend across all major web 2.0 social media, chat, email, sms etc... (aim to minimize trust issues related to asking people to click links)
- [ ] **Bonus:**  if you want to create a tutorial/detailed instructions in similar format to those in Vital Point Academy/on the blog you can negotiate compensation for that as well.

#### Coordinating Instructions

- free to submit interest in this proposal on a rolling basis even if assigned.  Would also encourage you to contact whomever it may be assigned to to offer/negotiate your assistance if interested
- create a new branch/submit pull request when ready
- please aim to reduce number of dependencies required
- must use React for UI
- prefer use of Material-UI for styling
- some educational material in [Vital Point Academy](https://vitalpoint.ai/academy/) and the [Vital Point AI blog](https://vitalpoint.ai/blog/) that can assist with getting familiar with NEAR and related technologies used (more to come...)

#### Contact

- discuss/ask questions in this issue
- reach out for assistance/clarification on [Discord](https://discord.gg/zufHrgHrts)
- reach out to me on Twitter (@Aaron_Luhning) or email (a.luhning@vitalpoint.ai)

**Comment by Em-kale** [comment]
Interested in taking on this bounty - have familiarized myself with the project, and am confident in my ability to deliver. 
Estimated delivery: Within 14-21 days. 
Working repository: Will commit changes to this fork of catalyst --  [](https://github.com/Em-kale/Catalyst.git)
Proposed payment: 130 NEAR (includes tutorial with video walk-through)

**Comment by Em-kale** [comment]
Update: well passed deadline, effort to finish this has been reinvigorated

**Comment by ALuhning** [comment]
I've merged the module, looks great.  Well done.

Just looking for the tutorial/video walk through to post to Vital Point Academy to payout the bounty based no your initial proposal.  I'll set you up with Vital Point Academy access.
